#!/usr/bin/perl
# $Id: cat2html,v 1.2 2011-04-05 15:58:09-07 - - $
#
# NAME
#    cat2html - convert input text to html, editing http: strings
#
# SYNOPSIS
#    cat2html [filename...]
#
# DESCRIPTION
#    Reads input files using <> and edits all strings of the form
#    http:\S+ replacing them with HREF links.  Write the generated
#    html to STDOUT.
#

my %htchars = qw (& &amp; < &lt; > &gt;);
print "<PRE>\n";

while (<>) {
   s/[&<>]/$htchars{$&}/g;
   s/(^|\b)(https?:\S+)/$1<A HREF=$2>$2<\/A>/g;
   print;
};

