#!/bin/sh
# $Id: jindent,v 1.2 2009-04-24 18:01:21-07 - - $
#
# NAME
#    jindent - reindent a Java program
#
# SYNOPSIS
#    jindent program.java...
#
# DESCRIPTION
#    Uses DrJava to reindent a java program using their
#    IndentFiles utility.
#
# FILES
#    /opt/local/drjava/
#
# BUGS
#    This script will break if a later version of DrJava 
#    is installed.
#

DRJPATH=/usr/local/drjava
VERSION=drjava-stable-20080904-r4668.jar
INDENT="edu.rice.cs.drjava.IndentFiles -indent 3"
java -cp $DRJPATH/$VERSION $INDENT $*
