#!/bin/sh
# $Id: letterbbox,v 1.3 2014-02-07 14:05:10-08 - - $
#
# Edit a Postscript file created by groff, and add a %%BoundingBox
# comment to make gv understand that it is Letter paper.
# Also, set the Title of the document.
#

for file in $*
do
   (echo 3a
    echo %%Title: $file
    echo %%BoundingBox: 0 0 612 792
    echo .
    echo w
    echo q) | ed $file
done

