#!/bin/sh
# $Id: mkc,v 1.82 2014-06-11 19:52:47-07 - - $
SCRIPT=`basename $0`
MANPAGE="#
# NAME
#    $SCRIPT - compile a C, C++, or Java program
#
# SYNOPSIS
#    $SCRIPT [-cdhgx] [-l lib]... prog.{c,cc,java}...
#
# DESCRIPTION
#    Check (ci) each source file into an RCS subdirectory and run
#    checksource to verify basic formatting.  This script only works
#    for simple programs entirely contained in one source file.
#    The object or class file(s) are then removed.
#
#    .c       - compile C.
#    .cc,.cpp - compile C++.
#    .m       - compiler Objective C.
#    .java    - compile Java, put in jar, including inner classes.
#
# OPTIONS
#    -c       Do not link C code, stop at -c, do not delete object file
#    -d       Do not delete the object or class files
#    -h       Print out man page information
#    -l lib   Add -llib to C/C++ compilation
#    -q       Quiet mode, no @@@@ chatter.
#    -x       Do not execute cid or checksource commands
#"

########################################################################
# Compilation options and shell variables.
#
GCC="gcc -g -O0 -Wall -Wextra -rdynamic -std=gnu11"
GPP="g++ -g -O0 -Wall -Wextra -rdynamic -std=gnu++11"
LIBS="-lglut -lGLU -lGL -lX11 -lrt -lm"

########################################################################
# Print a command then run it.  Exit failure if it fails.
#
runcmd() {
   echo $*
   $* 2>&1
   [ $? -eq 0 ] || exit 1
}

########################################################################
# Print the manpage and exit.
#
manpage() {
   echo "$MANPAGE" | sed -e 's/^# //' -e 's/^#//'
   exit 0
}

########################################################################
# Print a usage message and exit.
#
usage() {
   echo "Usage: $SCRIPT [-cdhlqx] prog.{c,cc,cpp,java}..." 1>&2
   exit 2
}

########################################################################
# Snip a suffix from a program name.
#
snip() {
   echo $1 | sed 's/\.[^.]*$//'
}

linkc() {
   if [ "$no_link_c" ] ; then echo -c ; else echo $* ; fi
}

########################################################################
# Compile a C program.
#
compile_c() {
   exec=`snip $source .c`
   runcmd $GCC $source `linkc -o $exec $LIBS`
   deletions="$exec.o"
}

########################################################################
# Compile a flex program and then compile C output.
#
compile_flex() {
   exec=`snip $source .l`
   runcmd flex --outfile=$exec.c $source
   runcmd $GCC $exec.c `linkc -o $exec $LIBS`
   deletions="$exec.o"
}

########################################################################
# Compile an Objective-C program.
#
compile_objc() {
   exec=`snip $source .c`
   runcmd $GCC $source `linkc -o $exec -lobjc $LIBS`
   deletions="$exec.o"
}

########################################################################
# Compile a C++ program.
#
compile_gpp() {
   exec=`snip $source`
   runcmd $GPP $source `linkc -o $exec $LIBS`
   deletions="$exec.o"
}

########################################################################
# Compile a Java program and put the classes in a jar.
#
compile_java() {
   exec=`snip $source`
   runcmd javac -Xlint $source
   echo Main-class: $exec >Manifest
   runcmd jar cfm $exec Manifest $exec*.class
   rm Manifest
   runcmd chmod +x $exec
   deletions="$exec*.class"
}

########################################################################
# Notify brackets around compilations.
#
notify() {
   [ $quiet ] || echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ $SCRIPT: $*
}

########################################################################
# Check for options.
#
while getopts cdhl:qx opt ; do
   case $opt in
      c) no_link_c=1; no_delete_obj=1;;
      d) no_delete_obj=1;;
      h) manpage;;
      l) LIBS="$LIBS -l$OPTARG";;
      q) quiet=1;;
      x) no_exec_cid=1;;
      ?) usage;;
   esac
done
shift $(($OPTIND-1))
[ $# -ne 0 ] || usage

########################################################################
# Compile each of the programs.
#
for source in $*
do
   notify starting $source
   if [ "$no_exec_cid" = "" ] ; then
      checksource $source
      cid + $source
      ident $source
   fi
   case $source in
      *.c)        compile_c;;
      *.l)        compile_flex;;
      *.m)        compile_objc;;
      *.cc)       compile_gpp;;
      *.cpp)      compile_gpp;;
      *.java)     compile_java;;
      *)          echo $SCRIPT: $source is not a known program type;;
   esac
   [ $no_delete_obj ] || runcmd rm -f $deletions
   notify finished $source
done

