#!/bin/sh
# $Id: mkrecheaders,v 1.4 2014-05-14 15:41:04-07 - - $
for dir in $@
do
   for subdir in $(find $dir -type d -name RCS -prune \
                          -o -type d -name '.?*' -prune \
                          -o -type d -print)
   do
      (cd "$subdir"; mkheader)
   done
done
