#!/usr/bin/perl
# $Id: noenv,v 1.2 2013-04-05 17:13:10-07 - - $
#
# NAME
#    noenv - run a program with no environment
#
# SYNOPSIS
#    noenv command operands...
#
# DESCRIPTION
#    Eliminates everything from the environment of the current
#    process then execs the command.

delete $ENV{$_} for keys %ENV;
exec @ARGV;
