#!/usr/bin/perl -p
# $Id: rot13,v 1.1 2008-10-01 14:50:48-07 - - $
# Rotate 13 (rot13) program:
# Rotate alphabet 13 places to encode or decode messages.
# http://en.wikipedia.org/wiki/ROT13
y/[a-zA-Z]/[n-za-mN-ZA-M]/
