#!/usr/bin/perl
# $Id: txt2html,v 1.18 2014-11-20 12:52:30-08 - - $
#
# NAME
#    txt2html - convert text file to html, editing http: strings
#
# SYNOPSIS
#    txt2html textfile
#
# DESCRIPTION
#    Reads textfile to replace strings of the form http:\S+*
#    with the directory name that it matches, if the directory
#    exists.  Creates an html file from the textfile by editing
#    all http: strings into an html link.  The file is created
#    with the suffix .txt or .text replaced by .html
#    It also converts the text file into Postscript and PDF.
#

use strict;
use warnings;

$0 =~ s|^(.*/)?([^/]+)/*$|$2|;
my $exit_status = 0;
END {exit $exit_status}
sub note(@) { print STDERR "$0: @_"; };
$SIG{'__WARN__'} = sub { note @_; $exit_status = 1; };
$SIG{'__DIE__'} = sub { warn @_; exit; };

if (@ARGV != 1) {
   print STDERR "Usage: $0 textfile\n";
   $exit_status = 1;
   exit
}

my $textname = shift;
open TEXTIN, "<$textname" or die "$textname: $!\n";
print STDERR "open <$textname: OK\n";
my @text = <TEXTIN>;
close TEXTIN;

for my $line (@text) {
   next unless $line =~ m/((^|\b)https?:)(\S+)\*/;
   my ($prefix, $dirpat) = ($1, $3);
   my $dir = glob "$dirpat*";
   next unless defined $dir and -d $dir;
   $line =~ s|$prefix$dirpat\*|$prefix$dir/|;
}

system "cid + $textname";
open TEXTOUT, ">$textname" or die "$textname: $!\n";
print TEXTOUT @text;
close TEXTOUT;

my %htchars = qw (& &amp; < &lt; > &gt;);
for my $line (@text) {
   $line =~ s|[&<>]|$htchars{$&}|g;
   $line =~ s{(^|\b)https?:\S+}{<A HREF=$&>$&</A>}g;
}

my $titlename = $textname;
$titlename =~ s/\.(txt|text|cat)$//;
my $htmlname = "$titlename.html";

my $pwd = `pwd`;
chomp $pwd;
$pwd =~ s|/afs/cats.ucsc.edu/courses/||;
my @headtext = <<__END_HEADTEXT__;
   <HEAD>
   <TITLE>~$pwd/$titlename</TITLE>
   <STYLE> 
   body {
      color: #2FFF2F !important;
      background-color: #2F2F2F !important;
   }
   table { 
      border: 2px solid;
      border-spacing: 0px;
   }
   td {
      border: 2px solid;
      padding: 3px;
      width: 14%;
      vertical-align: top;
   }
   A:link {color: #2FFFFF}
   A:visited {color: #FFFF2F}
   A:hover {color: #FF2F2F}
   </STYLE>
   </HEAD> 
   <BODY>
__END_HEADTEXT__
map {s/^   //} @headtext;

open HTMLOUT, ">$htmlname" or die "$htmlname: $!\n";
print STDERR "open >$htmlname: OK\n";
print HTMLOUT @headtext;
print HTMLOUT "<PRE>\n";
print HTMLOUT @text;
print HTMLOUT "</PRE>\n</BODY>\n";
close HTMLOUT;

system "ls -laofg $textname $htmlname";

