#!/usr/bin/perl
# $Id: unames,v 1.5 2013-04-09 18:04:46-07 - - $
#
# Print out the values of various unames options.
#



@options = (
  [qw (-a --all               )],
  [qw (-s --kernel-name       )],
  [qw (-n --nodename          )],
  [qw (-r --kernel-release    )],
  [qw (-v --kernel-version    )],
  [qw (-m --machine           )],
  [qw (-p --processor         )],
  [qw (-i --hardware-platform )],
  [qw (-o --operating-system  )],
);

for $opt (@options) {
   $value = `uname $opt->[0]`;
   chomp $value;
   printf "uname %-22s = %s\n", "@$opt", $value;
}

$release = "/etc/redhat-release";
print "$release: ", `cat $release` if -r $release;
